### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.comet.package$ 

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#1012]
### Describe the bug

I am building a Docker image using the Dockerfile from this repo and then trying to execute queries in k8s. I get the following error.

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.comet.package$
  at org.apache.comet.vector.NativeUtil.<init>(NativeUtil.scala:48)
  at org.apache.comet.CometExecIterator.<init>(CometExecIterator.scala:52)                         
```

As far as I can tell, the root cause is an exception being thrown in the following code:

```
package object comet {

  val CometArrowAllocator = new RootAllocator(Long.MaxValue)
```

**Comment by tbar4** [comment]
Getting a similar error:

```scala
scala> (0 until 10).toDF("a").write.mode("overwrite").parquet("/tmp/test")
24/10/11 19:32:10 WARN CometSparkSessionExtensions: Comet extension is disabled because of error when loading native lib. Falling back to Spark
java.lang.NoClassDefFoundError: Could not initialize class org.apache.comet.NativeBase
```

**Comment by andygrove** [comment]
> Getting a similar error:
> 
> ```scala
> scala> (0 until 10).toDF("a").write.mode("overwrite").parquet("/tmp/test")
> 24/10/11 19:32:10 WARN CometSparkSessionExtensions: Comet extension is disabled because of error when loading native lib. Falling back to Spark
> java.lang.NoClassDefFoundError: Could not initialize class org.apache.comet.NativeBase
> ```

There is a specific issue for the NativeBase error: https://github.com/apache/datafusion-comet/issues/999
