### ISSUE TITLE
Support partition values in feature branch comet-parquet-exec

### ISSUE THREAD

**Issue by viirya** [apache/datafusion-comet#1102]
### What is the problem the feature request solves?

On the feature branch `[comet-parquet-exec](https://github.com/apache/datafusion-comet/tree/comet-parquet-exec)` for exploring fully native scan, partition values are handled now so a few tests are failed in CometExecSuite due to that. So we should pass correct partition values from JVM to native.

**Comment by andygrove** [comment]
Closed by https://github.com/apache/datafusion-comet/pull/1106 (did not auto close because not merged to main branch)
