### ISSUE TITLE
Can get wrong results when querying Delta tables

### ISSUE THREAD

**Issue by Kimahriman** [apache/datafusion-comet#1121]
### Describe the bug

Because Delta scans work by using a subclass of `ParquetFileFormat` within a normal Hadoop relation, Comet will see this and simply replace it with a `CometParquetFileFormat`, losing all the Delta-specific things in it's own subclass, such as deletion vector support and column mapping

### Steps to reproduce

Don't have exact steps right now, noticed this randomly while testing things out and kind of expected this to be a problem.

### Expected behavior

If doing a Delta scan, it should not be eligible to be converted to a CometScan. The check for `ParquetFileFormat` probably needs to be an exact class comparison that doesn't include subclasses.

Longer term it would be interesting if it is possible to delegate the necessary behavior to custom file formats, but all the work trying to push down the Parquet scans to datafusion might make that impossible unless a different approach like using delta-rs directly is used such as in #174

**Comment by parthchandra** [comment]
> Longer term it would be interesting if it is possible to delegate the necessary behavior to custom file formats

I would hope that custom formats use Spark's DSV2 apis (like iceberg does). 

> all the work trying to push down the Parquet scans to datafusion might make that impossible 

true. CometParquetFileFormat will become unnecessary and Comet scan will become entirely native (or so we think).

**Comment by Kimahriman** [comment]
> I would hope that custom formats use Spark's DSV2 apis (like iceberg does).

It would be nice if that were the case but Databricks doesn't seem to have any interest in converting all their code to use the DSv2 APIs
