### ISSUE TITLE
Comet 0.3.0 jar file not present

### ISSUE THREAD

**Issue by SalcaE** [apache/datafusion-comet#1126]
### Describe the bug

I noticed that the file "comet-spark-spark3.4_2.12-0.3.0.jar" is not present in the "jars" folder inside the [image](https://github.com/apache/datafusion-comet/pkgs/container/datafusion-comet/280980297?tag=spark-3.4-scala-2.12-0.3.0) of version 0.3.0.

**Comment by andygrove** [comment]
Thanks for reporting this. This is a known issue that was fixed for the 0.4.0 release:

https://github.com/apache/datafusion-comet/pkgs/container/datafusion-comet/307947900?tag=spark-3.4-scala-2.12-0.4.0
