### ISSUE TITLE
Create a script to run TPC-H/clickBench locally

### ISSUE THREAD

**Issue by sunchao** [apache/datafusion-comet#141]
### What is the problem the feature request solves?

DataFusion has this script: https://github.com/apache/arrow-datafusion/blob/main/benchmarks/bench.sh which offers a convenient way to run local benchmarks such as TPC-H and clickbench and compare results across different branches. Maybe we can borrow it into Comet.

**Comment by andygrove** [comment]
We now have the [Comet Benchmarking Guide](https://datafusion.apache.org/comet/contributor-guide/benchmarking.html) and all of the TPC-H scripts are open source as part of the new [DataFusion Benchmarks](https://github.com/apache/datafusion-benchmarks) repo, so I think we can close this issue now.
