### ISSUE TITLE
Setup regular meetups for Comet development

### ISSUE THREAD

**Issue by parthchandra** [apache/datafusion-comet#217]
Since the project is new and we have a growing number of contributors, it might make sense to set up a regular online meetup where contributors can sync up.

What do other contributors think? Please provide suggestions on format, frequency and timing of meetups.

**Comment by viirya** [comment]
In my impression, these types of meeting are not effective eventually. So I wonder if it needs to be regular or it can be irregular (e.g., setting up a sync up meeting if something needs to be discussed face to face virtually?)

**Comment by andygrove** [comment]
We had bi-weekly DataFusion calls for a while, and they were certainly helpful to new contributors but we eventually stopped doing them. It was partly due to lack of availability of anyone to run the calls.

I think it could be useful at least in the short term to setup something similar for the Comet project, even if they don't continue longer term once the project has more momentum. I would be happy to help with them if that is useful. I would suggest bi-weekly, maybe 9am PT / early evening in Europe.

**Comment by viirya** [comment]
I was asked if we can provide QA session for potential contributors. Is this also a good place to hold such purpose? Maybe in first meeting.

**Comment by parthchandra** [comment]
> I was asked if we can provide QA session for potential contributors. Is this also a good place to hold such purpose? Maybe in first meeting.

Yes. If it builds a larger community, of course

I can work with Andy on setting something up.

**Comment by viirya** [comment]
Are we going to set up something with this?

**Comment by parthchandra** [comment]
@andygrove Any suggestions on how this was done for DF?

**Comment by andygrove** [comment]
> @andygrove Any suggestions on how this was done for DF?

Sure. We just need to pick a time/schedule and then send out an email on the mailing list and post to slack/discord etc.

There is a bi-weekly general Arrow meeting every other Wed at 16:00 UTC / 12:00 EDT / 9:00 PDT. We could hold ours at the same time on the alternate weeks.

**Comment by andygrove** [comment]
I have created a Google calendar invite on my personal gmail account. Here is a document with a link to the invite. 

https://docs.google.com/document/d/1NBpkIAuU7O9h8Br5CbFksDhX-L9TyO9wmGLPMe0Plc8/edit?usp=sharing

@viirya @parthchandra could you test this out and see if you are able to accept the invite?

**Comment by viirya** [comment]
I clicked the link of "Google Calendar Invite" in the doc, but it said "Couldn't find the requested event".

**Comment by andygrove** [comment]
> I clicked the link of "Google Calendar Invite" in the doc, but it said "Couldn't find the requested event".

The invite was private. I have now made it public. Could you try again?

**Comment by viirya** [comment]
> The invite was private. I have now made it public. Could you try again?

Hmm, still same error.

**Comment by parthchandra** [comment]
I'm also (still) getting the  "Couldn't find the requested event" . The Meet link seems to be working.

**Comment by parthchandra** [comment]
I'm sure we can manage half an hour earlier. @andygrove, @viirya  wdyt?

**Comment by andygrove** [comment]
> I'm sure we can manage half an hour earlier. @andygrove, @viirya wdyt?

I have updated the calendar invite and the document to reflect the new time.

Also, the invite is finally accessible.

**Comment by viirya** [comment]
> Also, the invite is finally accessible.

It still doesn't work for me. Same error.

**Comment by viirya** [comment]
Is this a possible fix for the error? 

https://stackoverflow.com/questions/60683012/google-calendar-could-not-find-the-requested-event

**Comment by andygrove** [comment]
<img width="596" alt="Screenshot 2024-04-30 at 12 26 47 PM" src="https://github.com/apache/datafusion-comet/assets/934084/5232e648-63c7-4360-acbb-6741eedbcc95">

<img width="540" alt="Screenshot 2024-04-30 at 12 29 48 PM" src="https://github.com/apache/datafusion-comet/assets/934084/acaf472a-c2c3-4e78-b6d2-6fec44689c22">
