### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by pingsutw** [apache/datafusion-comet#247]
### Describe the bug
https://arrow.apache.org/datafusion-comet

<img width="1688" alt="Screenshot 2024-04-07 at 2 50 50 AM" src="https://github.com/apache/arrow-datafusion-comet/assets/37936015/0bab554d-97b2-429d-8d1f-348592ae0770">

<img width="1248" alt="Screenshot 2024-04-07 at 2 51 28 AM" src="https://github.com/apache/arrow-datafusion-comet/assets/37936015/bed9091c-d74b-43f3-8e4a-b1c9d3e28a37">

**Comment by andygrove** [comment]
Thanks for the report. We have not published the documentation to the Apache site yet but we will get to this soon.

**Comment by andygrove** [comment]
> Thanks for the report. We have not published the documentation to the Apache site yet but we will get to this soon.

We will likely wait until the DataFusion project (and its subprojects, including Comet) moves to a top level Apache project in the next few weeks.

**Comment by andygrove** [comment]
Documentation will be published once https://github.com/apache/datafusion-comet/pull/314 is merged
