### ISSUE TITLE
Switch back to released version of DataFusion and arrow-rs after Arrow Java 16 is released

### ISSUE THREAD

**Issue by viirya** [apache/datafusion-comet#248]
### What is the problem the feature request solves?

In #239, we moved to use specified forked of DataFusion and arrow-rs as a temporary workaround to the Arrow Java bug which sends invalid offset buffers through C Data Interface.

The fix to the bug was merged to Arrow Java. Once Arrow Java 16 is released, we should move back to released versions of DataFusion and arrow-rs.

**Comment by andygrove** [comment]
Arrow 16 has now been released:

https://arrow.apache.org/release/16.0.0.html

**Comment by viirya** [comment]
Got it. Thanks.

**Comment by viirya** [comment]
I would like to hold this until #250 is merged. Assigned to myself.

**Comment by andygrove** [comment]
@viirya Is there anything stopping us from depending on the datafusion repo directly now (once https://github.com/apache/datafusion/pull/10702 is merged) rather than your fork?

**Comment by viirya** [comment]
Let me try to switch to official DataFusion repo.

**Comment by viirya** [comment]
There are some changes from latest DataFusion repo. I'm working on to update Comet with it.

**Comment by andygrove** [comment]
The release vote for arrow-rs 52 has started, and there is a draft PR in DataFusion to upgrade to this version:

https://github.com/apache/datafusion/pull/10765

**Comment by viirya** [comment]
Cool. I will update the PR accordingly once we get DataFusion and arrow-rs releases.
