### ISSUE TITLE
Remove "Execution error: " prefix from error messages from Rust

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#293]
### What is the problem the feature request solves?

We cannot exactly match Spark error messages in some cases because DataFusion is prefixing errors from Rust with "Execution error: ".

Because we are ultimately implementing traits from DataFusion, any `CometError`s we create get converted into DataFusion errors:

```rust
impl From<CometError> for DataFusionError {
    fn from(value: CometError) -> Self {
        match value {
            CometError::DataFusion { source } => source,
            _ => DataFusionError::Execution(value.to_string()),
        }
    }
}
```

In `errors.rs` we use [thiserror](https://crates.io/crates/thiserror) for formatting errors and we delegate formatting to DataFusion for `DataFusionError`:

```rust
#[error(transparent)]
DataFusion {
    #[from]
    source: DataFusionError,
},
```

DataFusion adds an "Execution error: " prefix in its formatting:

```rust
DataFusionError::Execution(ref desc) => {
    write!(f, "Execution error: {desc}")
}
```

### Describe the potential solution

There seem to be two options:

1. Add a new variant to DataFusionError which does not do any additional formatting and just returns the underlying error string
2. Find a work around in the mapping using thiserror

**Comment by comphead** [comment]
DF still returns formatted messages, `physical_plan.execute(...)?` will produce a formatted error message so we still have to live with that. 

If we looking for sending the Comet message to the user without additional wrapping into `Execution error:`, then `thiserror` can help. Another couple of options is hacky one to strip `Execution error: `, or make a separate method in DF for errors returning direct error messages. The last one imho better option. if you agree I'll create the PR to DF and see where it can bring us

**Comment by edmondop** [comment]
How about an environment variable? Is this too expensive to read every time ?

**Comment by comphead** [comment]
My naive approach was to fix the formatter and for some alignment case the prefix won't be added 
```
println!("{}", err) => Execution error: err
println!("{:>}", err) => err
```
But this solution looks incomplete to me as `to_string()` for example will format with default format....

**Comment by comphead** [comment]
Filed https://github.com/apache/datafusion/pull/10186

**Comment by comphead** [comment]
@andygrove we the proposed by @alamb approach we can do something like coded in https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4d0e0462ab6db7fa63e7791e941eea36

Notice `Exec err:` is gone.
Btw this is another question on why we do chain `CometError -> DataFusionError -> ExecutionError`

**Comment by comphead** [comment]
Depends on DF 38.0.0
