### ISSUE TITLE
Implement Spark-compatible CAST float/double to string

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#312]
### What is the problem the feature request solves?

We currently delegate to DataFusion when casting float/double to string and there are some differences in behavior compared to Spark.

- Spark uses `Infinity` and `-Infinity` and DataFusion uses `inf` and `-inf`
- Spark uses `E` for exponent and DataFusion uses `e`

There can also be differences in formatting but where the values are semantically equivalent. For example, for the input `1.0499721536516571E-4`:

Spark produces `"1.0499721536516571E-4"`
DataFusion produces: `"0.00010499721536516571"`

We should create a compatibility guide and include this information.

Here are some suggested values to test:

```scala
val testData = Seq(Float.NegativeInfinity, Float.PositiveInfinity,
      Float.MinPositiveValue, Float.MinValue, Float.MaxValue, Float.NaN, -0.0f, 0.0f)
```

**Comment by mattharder91** [comment]
Can I try this one out?

**Comment by viirya** [comment]
Of course. Thanks @mattharder91. Please let us know if you have any question.

**Comment by mattharder91** [comment]
Here you go https://github.com/apache/datafusion-comet/pull/346
