### ISSUE TITLE
explain plan disables some cases in ScanExecRule

### ISSUE THREAD

**Issue by parthchandra** [apache/datafusion-comet#322]
### Describe the bug

A new case was added in ScanExecRule to add explain info if the DSV2 source scan was not parquet. However, this overrides an existing case which matched non parquet DSV2 sources like Iceberg. 

### Steps to reproduce

No clear way to produce this. Discovered when developing support for iceberg

**Comment by parthchandra** [comment]
Closing. Fixed by #302

**Comment by jc4x4** [comment]
just reminder you forgot to actually close this.

**Comment by viirya** [comment]
Closed it now. Thanks @jc4x4 for reminding.
