### ISSUE TITLE
chore: Use enum to represent CAST eval_mode in expr.proto

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#361]
### What is the problem the feature request solves?

When I added `eval_mode` to the `Cast` message in `expr.proto` I defined it as a string but it should really be an enum.

```protobuf
enum EvalMode {
  LEGACY = 0;
  TRY = 1;
  ANSI = 2;
}
```

**Comment by prashantksharma** [comment]
@andygrove 

Thank you for the description. 

I would like to work on this issue.

**Comment by viirya** [comment]
Definitely yes. Thanks @prashantksharma

**Comment by parthchandra** [comment]
I suppose for this issue it is okay to violate the rule to not modify a field in a protobuf message because we haven't published anything yet.

**Comment by andygrove** [comment]
> I suppose for this issue it is okay to violate the rule to not modify a field in a protobuf message because we haven't published anything yet.

Yes, absolutely.

**Comment by prashantksharma** [comment]
@andygrove , cc: @viirya 

## Minor Query before opening PR

<ins>Summary</ins>: 
- Have made changes to `expr.proto` and `QueryPlanSerde.scala`. The changes have been pushed to a separate branch on my fork. The comparison can be seen [here](https://github.com/apache/datafusion-comet/compare/main...prashantksharma:datafusion-comet:issue-361-enum-for-eval_mode): 
- `make test-rust` gives following error. 

![Screenshot 2024-05-04 at 16 15 58](https://github.com/apache/datafusion-comet/assets/5937244/a0476744-148d-4a9a-99a2-dabd4574237d)


<ins>Minor Query</ins>:
Before opening the PR, I wanted to confirm, if I should go ahead and resolve the error for `planner.rs` or a separate issue needs to be created for this ?

**Comment by andygrove** [comment]
On the Rust side you will need a `match` statement to convert the protobuf i32 to the Rust enum (0 -> legacy, 1 -> try, 2 -> ansi). Perhaps take a look at how we handle one of the other enums defined in the proto and follow the same pattern?

**Comment by andygrove** [comment]
@prashantksharma also, feel free to create a draft PR as it can be easier for maintainers to make suggestions on the PR

**Comment by prashantksharma** [comment]
@andygrove 

Thank you so much for your feedback:

> On the Rust side you will need a match statement to convert the protobuf i32 to the Rust enum (0 -> legacy, 1 -> try, 2 -> ansi). Perhaps take a look at how we handle one of the other enums defined in the proto and follow the same pattern?

I will make updates based on my understanding of the above comment by you. 

 And, Thank you for your suggesting creation of draft PR, after making necessary updates, I will do that.

**Comment by prashantksharma** [comment]
@andygrove cc: @viirya 

I have opended a draft PR. 

I have tested the changes using 
- `make test-rust`
- `make test-jvm`

Details on PR message:https://github.com/apache/datafusion-comet/pull/415
