### ISSUE TITLE
Plan Comet 0.1.0 Release

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#369]
### What is the problem the feature request solves?

During the Comet public meeting this morning, there were questions about when the first official release would be. We do not really have an answer to that yet, but we can use this issue to discuss it.

Here are some ideas for milestones that we may want to achieve before creating an official source release (note that we do not necessarily need to create binary releases right away).

- [x] Demonstrate performance improvements with benchmarks derived from TPC-H
- [x] Demonstrate performance improvements with benchmarks derived from TPC-DS - https://github.com/apache/datafusion-comet/pull/687
- [x] https://github.com/apache/datafusion-comet/issues/394
- [x] https://github.com/apache/datafusion-comet/issues/459
- [x] https://github.com/apache/datafusion-comet/issues/248
- [x] https://github.com/apache/datafusion-comet/issues/142
- [x] https://github.com/apache/datafusion-comet/pull/657
- [x] https://github.com/apache/datafusion-comet/pull/656

Nice to have:

- [ ] https://github.com/apache/datafusion-comet/issues/510
- [ ] https://github.com/apache/datafusion-comet/issues/387
- [ ] https://github.com/apache/datafusion-comet/issues/596

Post-release items:

- [ ] https://github.com/apache/datafusion-comet/issues/524 (this affects the web site not the release tarball)
- [ ] Prepare blog post announcing the release. Google doc for collaborating on this is [here](https://docs.google.com/document/d/1rnxnbi66oFr5B-OTUxtpi9pnifOxNkmvOVIRTN0BfhY/edit?usp=sharing).

**Comment by parthchandra** [comment]
> * Ensure that currently supported operators and expressions are fully compatible with all supported Spark versions

I think this is good requirement for the first release

>  * Achieve 100% coverage for TPC-H and/or TPC-DS benchmark with a clear performance advantage

TPC-H for sure. TPC-DS may be a stretch goal.

**Comment by andygrove** [comment]
One benefit of creating a release is that it is a good opportunity to write a blog post to announce the release and provide an update on the status of the project, and try and encourage more people to contribute. It can also demonstrate the momentum that the project has. I suppose I am now making an argument against waiting until we have great benchmark results before making the first release. I would be interested to hear opinions on this.

**Comment by andygrove** [comment]
I propose that we create the 0.1.0 source release as soon as we have upated the project to use the upcoming DataFusion 39.0.0 release which should be avalable around June 10.

**Comment by viirya** [comment]
+1. But we may need new arrow-rs release 52.0.0 too. Will it be released before DataFusion 39.0.0?

**Comment by andygrove** [comment]
Here is the tracking issue for arrow-rs 52: https://github.com/apache/arrow-rs/issues/5688

It should be available next week. I updated the DataFusion 39 release issue to add this to the prerequisites for the release: https://github.com/apache/datafusion/issues/10517

**Comment by andygrove** [comment]
I created a Google doc for the community to collaborate on a blog post announcing the release:

https://docs.google.com/document/d/1rnxnbi66oFr5B-OTUxtpi9pnifOxNkmvOVIRTN0BfhY/edit?usp=sharing

**Comment by viirya** [comment]
We plan to do binary release, although it might not be able to catch up the 0.1.0 source release. Publishing to Maven repo needs more works to do. Comet involves native code, so it becomes more complicated than pure Java/Scala projects. We need to include pre-built binaries for different platforms in the published jar.

**Comment by parthchandra** [comment]
I assume the source release will tag the repo with a `release-0.1.0` tag. Even though a maven artifact would not be published, it does allow projects to build their own, or even add comet as a git submodule, based on a relatively 'stable' version.

**Comment by andygrove** [comment]
> I assume the source release will tag the repo with a `release-0.1.0` tag. Even though a maven artifact would not be published, it does allow projects to build their own, or even add comet as a git submodule, based on a relatively 'stable' version.

Yes, absolutely. We (or anyone) can choose to release binary artifacts from the source release or the tag in the repo. ASF does not have any special involvement in that.

**Comment by andygrove** [comment]
I created a milestone where we can track the priority issues for the 0.1.0 release

https://github.com/apache/datafusion-comet/milestone/1

**Comment by andygrove** [comment]
I think we are getting close to being able to release 0.1.0 now that we are using an official DataFusion release again (or will be in a few days when DF 40 is released to crates.io).

There a few remaining issues in the [0.1.0 milestone](https://github.com/apache/datafusion-comet/milestone/1), the most important ones (IMO) being:

- https://github.com/apache/datafusion-comet/issues/524
- https://github.com/apache/datafusion-comet/issues/387

@parthchandra @viirya is there anything else that you think we need to address for the first source release?

**Comment by viirya** [comment]
>  is there anything else that you think we need to address for the first source release?

No. I think the above two issues are most notable at the moment.

**Comment by parthchandra** [comment]
> > is there anything else that you think we need to address for the first source release?
> 
> No. I think the above two issues are most notable at the moment.

I think this is good.

**Comment by andygrove** [comment]
@viirya @parthchandra I no longer think that it is critical to fix https://github.com/apache/datafusion-comet/issues/387 before we release, because users can already enable shuffle, so this is just a config change from user point of view.

If there are no objections, I will plan on creating 0.1.0-rc1 next week, after review documentation to make sure all known issues are documented.

**Comment by viirya** [comment]
+1

**Comment by parthchandra** [comment]
> I no longer think that it is critical to fix #387 before we release, because users can already enable shuffle, so this is just a config change from user point of view.
> 
Agreed
