### ISSUE TITLE
Write a guide on contributing a new expression

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#370]
### What is the problem the feature request solves?

We should write a detailed guide showing new contributors how to add support for a new expression in Comet. This would cover the Scala, Protobuf, and Rust changes, as well as testing approaches. We could create this based on a recent PR that added a new expression.

**Comment by tshauck** [comment]
Once https://github.com/apache/datafusion-comet/pull/342 is approved/merged and if it's an appropriate example, I'd be happy to write this based off that work.

**Comment by parthchandra** [comment]
Also related to adding a new expression is adding a new _aggregate expression_ (for example: https://github.com/apache/datafusion-comet/commit/49bf503780dfc93ede968b626214d53fb0953c34)

**Comment by andygrove** [comment]
And I suppose we also need a separate guide on adding cast expressions since there are specific test considerations

**Comment by andygrove** [comment]
This was completed: https://datafusion.apache.org/comet/contributor-guide/adding_a_new_expression.html
