### ISSUE TITLE
Implement Spark-compatible CAST from floating-point to decimal

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#371]
### What is the problem the feature request solves?

Comet's implementation of CAST float/double to Decimal delegates to DataFusion and is not compatible with Spark.

The following test in `CometCastSuite` can be used to see the current failures.

```scala
  ignore("cast DoubleType to DecimalType(10,2)") {
    // Comet should have failed with [NUMERIC_VALUE_OUT_OF_RANGE]
    castTest(generateDoubles(), DataTypes.createDecimalType(10, 2))
  }
```

**Comment by vaibhawvipul** [comment]
I would like to work on this.
