### ISSUE TITLE
Add support for TryCast expression in Spark 3.2 and 3.3

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#374]
### What is the problem the feature request solves?

Spark 3.2 and 3.3 has a `TryCast` expression and Spark 3.4 removed it and added an `evalMode` parameter to the `Cast` expression.

We do not support the `TryCast` expression and should add support. This was missed until now because `CometCastSuite` calls `checkSparkAnswer` instead of `checkSparkAnswerAndOperator`.

**Comment by vaibhawvipul** [comment]
I am working on this one.
