### ISSUE TITLE
feat: Add support for BuildRight

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#390]
### What is the problem the feature request solves?

We are unable to run a number of TPC-H natively due to the error `BuildRight is not supported`. The queries affected include q2, q9, q10, q11, and q16.

See code in `QueryPlanSerde`.

```
if (join.buildSide == BuildRight) {
  // DataFusion HashJoin assumes build side is always left.
  // TODO: support BuildRight
  withInfo(join, "BuildRight is not supported")
  return None
}
```

**Comment by andygrove** [comment]
Related issue in DataFusion: https://github.com/apache/datafusion/issues/9603

**Comment by viirya** [comment]
I will work on this at DataFusion.
