### ISSUE TITLE
bug: CAST string to integer does not handle all invalid inputs

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#431]
### Describe the bug

PR https://github.com/apache/datafusion-comet/pull/426 improved the fuzz testing in CometCastSuite and found a new issue with CAST from string to integer. Tests have been ignored and those casts marked as incompatible.

This issue is to reinstate the tests, mark as compatible, and fix the failures.

**Comment by vaibhawvipul** [comment]
I am working on this.
