### ISSUE TITLE
chore: extended explain info can be an object instead of class

### ISSUE THREAD

**Issue by parthchandra** [apache/datafusion-comet#452]
### Describe the bug

ExtendedExplainInfo is declared as a class, but it can be an object instead.

**Comment by vaibhawvipul** [comment]
taking this up

**Comment by vaibhawvipul** [comment]
We can close this one.

**Comment by parthchandra** [comment]
Thanks for checking @andygrove I think I opened this issue originally to follow up on a review comment.

**Comment by andygrove** [comment]
I think we can close this one now
