### ISSUE TITLE
bug: null character not permitted in chr function

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#479]
### Describe the bug

The following query ran without error in Spark but failed in Comet. I discovered this bug using [Comet Fuzz](https://github.com/apache/datafusion-comet/pull/472).

```
SELECT chr(c9),chr(c4) FROM test0
```

```
Query failed in Comet: Job aborted due to stage failure: Task 13 in stage 83.0 failed 1 times, most recent failure: Lost task 13.0 in stage 83.0 (TID 749) (192.168.86.33 executor driver): org.apache.comet.CometNativeException: Execution error: null character not permitted.
```

**Comment by vaibhawvipul** [comment]
I am working on this.

**Comment by vaibhawvipul** [comment]
@andygrove I am not able to reproduce it, can you please help me out? I have raised a draft PR where I have added a test cases which uses null charecters in chr function.

**Comment by vaibhawvipul** [comment]
> I think the invalid input is 0, so datafusion refuses
> 
> ```
> > select chr(0);
> Execution error: null character not permitted.
> ```
> 
> To be compatible with that, we have to re implement chr in comet.

Hey! I am able to repro this bug now. Thanks :)
