### ISSUE TITLE
bug: upper and lower not compatible with Spark for international character sets

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#483]
### Describe the bug

I discovered this bug using [Comet Fuzz](https://github.com/apache/datafusion-comet/pull/472).

```sql
SELECT lower(c2) FROM test0
```

[ERROR] Spark and Comet produced different results.

### Spark Plan

```
*(1) Project [lower(c2#2) AS lower(c2)#1546]
+- *(1) ColumnarToRow
   +- FileScan parquet [c2#2] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/Users/andy/git/apple/comet-fuzz/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c2:string>
```

### Comet Plan

```
*(1) ColumnarToRow
+- CometProject [lower(c2)#1550], [lower(c2#2) AS lower(c2)#1550]
   +- CometScan parquet [c2#2] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/Users/andy/git/apple/comet-fuzz/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c2:string>
```

### Results 

Spark produced 200 rows and Comet produced 200 rows.
First difference at row 91:
Spark: `[ሽ븃靛脉项ໍ绹跅]`
Comet: `[ძ訆喀ꓚ疟⓰⡃婳]`

**Comment by Lordworms** [comment]
interested in this one.

**Comment by Lordworms** [comment]
Hi @andygrove  Could you please provide the actual setup for this query? since I tried it locally to compare the differences between comet and raw spark, it appears to be the same.
![image](https://github.com/apache/datafusion-comet/assets/48054792/42d1c165-d88c-4b37-b1c8-d0f15b0799e1)

**Comment by andygrove** [comment]
Here is another example:

```
First difference at row 95:
Spark: `Ჹ퓎墡勝䴿㿣䧛㰏,Ჹ퓎墡勝䴿㿣䧛㰏`
Comet: `Ჹ퓎墡勝䴿㿣䧛㰏,ჹ퓎墡勝䴿㿣䧛㰏`
```

Java has locale-specific behavior for converting to upper and lower case, and Rust does not. We cannot expect them to produce the same results in all cases.
