### ISSUE TITLE
bug: signum produces different values than Spark in some cases

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#486]
### Describe the bug

I discovered this bug using [Comet Fuzz](https://github.com/apache/datafusion-comet/pull/472).

```sql
SELECT Signum(c6) FROM test1
```

[ERROR] Spark and Comet produced different results.
### Spark Plan
```
*(1) Project [SIGNUM(cast(c6#26 as double)) AS SIGNUM(c6)#18070]
+- *(1) ColumnarToRow
   +- FileScan parquet [c6#26] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/Users/andy/git/apple/comet-fuzz/test1.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c6:tinyint>

```
### Comet Plan
```
*(1) ColumnarToRow
+- CometProject [SIGNUM(c6)#18074], [SIGNUM(cast(c6#26 as double)) AS SIGNUM(c6)#18074]
   +- CometScan parquet [c6#26] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/Users/andy/git/apple/comet-fuzz/test1.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c6:tinyint>

```
### Results 
Spark produced 200 rows and Comet produced 200 rows.
First difference at row 87:
Spark: `[0.0]`
Comet: `[1.0]`

**Comment by abrassel** [comment]
Mind if i take this @andygrove ? This is my first contribution to comet but I would love to learn more about the tool.

**Comment by andygrove** [comment]
> Mind if i take this @andygrove ? This is my first contribution to comet but I would love to learn more about this project.

@abrassel Please go ahead. Let me know if you have any questions

**Comment by abrassel** [comment]
Hi @andygrove sorry for not getting around to it! Work and personal life sharply picked up. Glad you were able to get the issue resolved.
