### ISSUE TITLE
Error E0554 during the installation

### ISSUE THREAD

**Issue by YannMoisan** [apache/datafusion-comet#494]
### Describe the bug

I've encountered errors during the installation.

### Steps to reproduce

This command `make release PROFILES="-Pspark-3.4"` triggers the following errors

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/lib.rs:23:34
   |
23 | #![cfg_attr(feature = "nightly", feature(core_intrinsics))]
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/lib.rs:24:1
   |
24 | #![feature(specialization)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: the feature `core_intrinsics` is internal to the compiler or standard library
  --> src/lib.rs:23:42
   |
23 | #![cfg_attr(feature = "nightly", feature(core_intrinsics))]
   |                                          ^^^^^^^^^^^^^^^
   |
   = note: using it is strongly discouraged
   = note: `#[warn(internal_features)]` on by default

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/lib.rs:23:42
   |
23 | #![cfg_attr(feature = "nightly", feature(core_intrinsics))]
   |                                          ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
warning: `comet` (lib) generated 1 warning
error: could not compile `comet` (lib) due to 3 previous errors; 1 warning emitted
make: *** [release] Error 101
```

### Additional context

```
❯ sw_vers
ProductName:	macOS
ProductVersion:	12.6.2
```

```
❯ cargo -V
cargo 1.77.1
```

**Comment by tshauck** [comment]
Others can comment, but it looks like you're trying to build Comet with stable rust and I think currently Comet requires `nightly`. Maybe your environment isn't picking-up the https://github.com/apache/datafusion-comet/blob/6ea5a427eab1e93a8fc10e7cf76a6b14ba2f0c18/rust-toolchain file?

**Comment by viirya** [comment]
> error[E0554]: `#![feature]` may not be used on the stable release channel

https://stackoverflow.com/questions/53136717/errore0554-feature-may-not-be-used-on-the-stable-release-channel-couldnt

Maybe you don't have installed `nightly` Rust compiler.

**Comment by YannMoisan** [comment]
I've installed a few months ago rust with `brew install rust`.

By running `brew unistall rust` and following instructions on https://doc.rust-lang.org/cargo/getting-started/installation.html

```
curl https://sh.rustup.rs -sSf | sh
rustup toolchain install nightly
```

It now works as expected.

**Comment by viirya** [comment]
Thank you @YannMoisan @tshauck.

Let me close this issue. Please let us know if you have other questions.

**Comment by andygrove** [comment]
For anyone else hitting this, here is a PR to make Comet use stable Rust: https://github.com/apache/datafusion-comet/pull/505
