### ISSUE TITLE
perf: Optimize some functions to rewrite dictionary-encoded strings

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#504]
### What is the problem the feature request solves?

We have some functions that unpack dictionary-encoded strings and then perform a transformation on the unpacked array, but it would be better to transform the dictionary instead. We should optimize these functions to do that.

The functions include:

- hex
- cast string to other types

There may be others.

**Comment by vaibhawvipul** [comment]
I would like to take this up, if no one else is working on it.
