### ISSUE TITLE
Add tests for Scalar and Inverval values for UnaryMinus

### ISSUE THREAD

**Issue by kazuyukitanimura** [apache/datafusion-comet#508]
### Describe the bug

Related to #471, we should add tests for Scalar and Inverval values for UnaryMinus

**Comment by vaibhawvipul** [comment]
I will work on this.

**Comment by kazuyukitanimura** [comment]
Thank you @vaibhawvipul assigned this to you

**Comment by vaibhawvipul** [comment]
@kazuyukitanimura I have added scalar tests, and I have also verified that it hits scalar path in the negative.rs code. Please review when you get a chance.
