### ISSUE TITLE
Modulus can produce incorrect results in some cases

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#521]
### Describe the bug

Example of compatibility issue found by fuzz testing:

```
SELECT c90, c1, c90 % c1 FROM test1 ORDER BY c90, c1;
```

Spark: `-21840,-0.0,NULL`
Comet: `-21840,-0.0,NaN`

**Comment by vaibhawvipul** [comment]
working on it.

**Comment by vaibhawvipul** [comment]
@andygrove so, spark treats just -0.0 (Float64) differently. The above behaviour is not observed for -0. 

Should i just add a special case that whenever we see -0.0 in divisor, we return scalar null?

**Comment by vaibhawvipul** [comment]
issue filed - https://github.com/apache/datafusion/issues/11051

**Comment by vaibhawvipul** [comment]
another one - https://github.com/apache/datafusion/issues/11108
