### ISSUE TITLE
Investigate TPC-H queries that are slower when Comet is enabled

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#530]
### What is the problem the feature request solves?

Our recent benchmarks show that most TPC-H queries were faster with Comet enabled, but q14, q16, and q19 were slower. We should try and understand why this is and see if we can make all queries faster. It would be nice if we could do this in time for the 0.1.0 release.

![](https://datafusion.apache.org/comet/_static/images/tpch_queries_speedup.png)

Specific issues:

- https://github.com/apache/datafusion-comet/issues/573
- https://github.com/apache/datafusion-comet/issues/569
- https://github.com/apache/datafusion-comet/issues/572

**Comment by vaibhawvipul** [comment]
I am working on this
