### ISSUE TITLE
Dropping Spark 3.2 support

### ISSUE THREAD

**Issue by huaxingao** [apache/datafusion-comet#565]
As we actively work on enhancing Comet by adding support for the latest Apache Spark 3.5, and with the upcoming release of Spark 4.0, I propose that we discontinue support for the older Spark 3.2 version. This change will reduce the burden of maintaining compatibility across multiple versions of Spark, allowing us to focus our efforts on integrating and optimizing for the most current releases. Please share any concerns or questions you may have regarding this proposal.

**Comment by andygrove** [comment]
+1

**Comment by viirya** [comment]
+1 if no others have strong demand on Spark 3.2 support.

**Comment by huaxingao** [comment]
also cc @sunchao @kazuyukitanimura @parthchandra

**Comment by parthchandra** [comment]
I'm +1 on this too. Maintaining more than two versions definitely slows down development.

**Comment by kazuyukitanimura** [comment]
+1
It might be a good idea to post the link of this issue on ASF slack `#datafusion-comet` channel to notify more folks

**Comment by eejbyfeldt** [comment]
+1

**Comment by sunchao** [comment]
+1
