### ISSUE TITLE
Improve error "BroadcastExchange is not supported"

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#568]
### What is the problem the feature request solves?

I sometimes see the error `BroadcastExchange is not supported,` which is confusing because Comet does support broadcast exchange in some cases, and the error doesn't explain why it is not supported in this case.

The error comes from the catch-all block in QueryPlanSerde.

I currently see this error with TPC-H q16.

**Comment by andygrove** [comment]
@parthchandra Are you interested in working on this one?

**Comment by parthchandra** [comment]
Yes, I'll take this up.
