### ISSUE TITLE
Infinite recursion when calling `canonicalized` on query plan for TPC-H q8

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#576]
### Describe the bug

_Note: This was originally reported as an issue with xxhash64 in https://github.com/apache/datafusion-comet/issues/517 but xxhash64 is not really involved._

When running TPC-H q8 with xxhash64 enabled, the executor becomes unresponsive, with most cores at 100%. Running a `kill -QUIT` command against the process dumps the current JVM stacks and shows a 500+ line stack performing plan transformation that appears to be the issue.

See attached log.

[executor-thread-dump.txt.gz](https://github.com/user-attachments/files/15844400/executor-thread-dump.txt.gz)

**Comment by andygrove** [comment]
The issue seems to be that `doCanonicalized` runs forever for this query.

**Comment by viirya** [comment]
Hmm, interesting. I will take a look.
