### ISSUE TITLE
Improve CometExchange metrics

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#625]
### What is the problem the feature request solves?

To make it easier to compare Spark and Comet in the Spark UI, I would find it helpful if Comet reported the following metrics:

- shuffle write time
- shuffle bytes written

![Screenshot from 2024-07-03 08-57-35](https://github.com/apache/datafusion-comet/assets/934084/7396b107-4c52-44ea-b018-296aaa184ee5)

**Comment by viirya** [comment]
Hmm, let me see how I can improve this.

**Comment by viirya** [comment]
Hmm, I think we already have `shuffleNativeTotalTime` which is `shuffle write time`, no?

**Comment by viirya** [comment]
Okay, I think `shuffle write time` is more like a e2e measure for the time on entire shuffle operation. `shuffleNativeTotalTime` focuses only on the time spent on native code execution.
