### ISSUE TITLE
Run miri  checks in CI

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#634]
### What is the problem the feature request solves?

We should run the miri checker in CI to help ensure that our unsafe code is actually safe.

See https://github.com/rust-lang/miri for instructions.

**Comment by vaibhawvipul** [comment]
@andygrove This is great! Thank you for implementing this. I have a question though, why did we decide to go with Miri? Why not say verus or kani?

**Comment by andygrove** [comment]
> @andygrove This is great! Thank you for implementing this. I have a question though, why did we decide to go with Miri? Why not say verus or kani?

I learned about using Miri with Rust when reading the new book "Effective Rust" from O'Reilly. I have not heard of verus or kani. I would be interested to learn more.
