### ISSUE TITLE
Create a Comet dockerfile 

### ISSUE THREAD

**Issue by comphead** [apache/datafusion-comet#643]
### What is the problem the feature request solves?

I would like to run the Comet accelerator with Spark in Kube environment, I would like to have instructions and dockerfile

**Comment by lmouhib** [comment]
@comphead do you need help with this?

**Comment by comphead** [comment]
Thanks @lmouhib, the dockerfile to build comet with spark is done, I'm trying to let it run in local kubectl this next week
