### ISSUE TITLE
Re-implement support for count in window aggregate

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#645]
### What is the problem the feature request solves?

When upgrading to DataFusion 40.0.0-rc1 in https://github.com/apache/datafusion-comet/pull/644 I had to disable support for count in windows aggregate because count is no longer a built-in function.

This issue is to track re-enabling this support.

**Comment by viirya** [comment]
cc @huaxingao

**Comment by huaxingao** [comment]
Looks like `min` and `max` will be removed from built-in function as well. I will re-implement the window aggregate support using `AggregateUDF`
