### ISSUE TITLE
Read Iceberg table is not support

### ISSUE THREAD

**Issue by dpengpeng** [apache/datafusion-comet#694]
### Describe the bug

Hello,I saw on the official website that the Iceberg table is supported,but when I tested to read the Iceberg table data,the result was that it was “BatchScan xxx is not supported”. Is my method wrong?

**Comment by dpengpeng** [comment]
@viirya Hi, could you tell me the current status of Comet's connection with Iceberg?

**Comment by huaxingao** [comment]
@dpengpeng We still need to have a Comet binary release for Iceberg to use Comet. The iceberg integration PR has not been merged yet. I will keep you updated on this.
