### ISSUE TITLE
Warnings about illegal reflective access

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#751]
### Describe the bug

I noticed this while running some benchmarks. I assume that this is a side-effect of the changes in https://github.com/apache/datafusion-comet/pull/723.

We may want to consider reverting this unless we can suppress these warnings.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/andy/.m2/repository/org/apache/spark/spark-unsafe_2.12/3.4.3/spark-unsafe_2.12-3.4.3.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by parthchandra** [comment]
I don't think reverting this is needed. 
This warning can be suppressed with the JVM option [--add-opens](https://docs.oracle.com/en/java/javase/17/migrate/migrating-jdk-8-later-jdk-releases.html#GUID-12F945EB-71D6-46AF-8C3D-D354FD0B1781)
Note that with JDK 17, Spark already needs to include `--add-opens=java.base/java.nio=ALL-UNNAMED`  which should suppress this warning.
