### ISSUE TITLE
Error in building using the release or from source - build failure

### ISSUE THREAD

**Issue by zelda89** [apache/datafusion-comet#763]
### Describe the bug

An error is encountered in building from source or the release. Spark version 3.4.3, JDK 22.0.1, Apple Silicon
<img width="562" alt="Screenshot 2024-08-01 at 10 21 06 PM" src="https://github.com/user-attachments/assets/2e3f8f32-2e27-41f5-be34-7126bcbcea69">

### Steps to reproduce

Followed the installation instructions - https://datafusion.apache.org/comet/user-guide/installation.html

**Comment by andygrove** [comment]
Spark 3.4 only supports Java 8, 11, and 17. Could you try with 17?

**Comment by zelda89** [comment]
Thanks! that worked, might be helpful to update the documentation.
