### ISSUE TITLE
Implement cast from struct type to string

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#814]
### What is the problem the feature request solves?

Casting from struct to string should be similar to the to_json code

**Comment by adi-kmt** [comment]
Hey @andygrove would like to take this issue up?

**Comment by adi-kmt** [comment]
Hey @andygrove are we talking about casts similar to [here](https://github.com/apache/datafusion-comet/blob/380f03d067b7703adefd3dce1849d9709bad3da9/native/spark-expr/src/cast.rs#L601)

**Comment by adi-kmt** [comment]
we're talking about this [PR](https://github.com/apache/datafusion-comet/pull/805/files#diff-1330a628b9d525dd0f5f24e21add2864a1680dfa018592d56d48e37516bba7af) right?

**Comment by andygrove** [comment]
> we're talking about this [PR](https://github.com/apache/datafusion-comet/pull/805/files#diff-1330a628b9d525dd0f5f24e21add2864a1680dfa018592d56d48e37516bba7af) right?

Yes, that is correct

**Comment by adi-kmt** [comment]
Hey @andygrove, sorry about that got a bit busy in office work and couldn't finish this task
