### ISSUE TITLE
Add support for ObjectHashAggregateExec

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#845]
### What is the problem the feature request solves?

We currently cannot run all TPC-H queries natively because we do not yet support ObjectHashAggregateExec. See q7 for an example.

**Comment by viirya** [comment]
Hmm, `ObjectHashAggregateExec` is used to support `TypedImperativeAggregate` which uses arbitrary JVM objects as aggregation states. I doubt that if we can make a native counterpart to it.

**Comment by andygrove** [comment]
> Hmm, `ObjectHashAggregateExec` is used to support `TypedImperativeAggregate` which uses arbitrary JVM objects as aggregation states. I doubt that if we can make a native counterpart to it.

We can't run arbitrary JVM objects, but we can provide native versions for known aggregates provided by Spark. TPC-H uses it for a `bloom_filter_agg`, for example, so we can implement an equivalent aggregate natively.
